[package]
name = "atadma-rs"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.58"
features= [
    "Win32_System_IO",
    "Win32_System_Ioctl",
    "Win32_Storage_FileSystem",
    "Win32_Security",
    "Win32_Foundation"
]