array_width = 120
attr_fn_like_width = 120
binop_separator = "Back"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
chain_width = 120
combine_control_expr = false
condense_wildcard_suffixes = false
edition = "2021"
empty_item_single_line = false
enum_discrim_align_threshold = 100
fn_params_layout = "Compressed"
fn_call_width = 120
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = true
format_macro_matchers = true
format_macro_bodies = true
hard_tabs = true
hex_literal_case = "Preserve"
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
inline_attribute_width = 120
match_arm_blocks = false
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
max_width = 140
merge_derives = true
imports_granularity = "Crate"
newline_style = "Native"
normalize_comments = false
normalize_doc_attributes = false
overflow_delimited_expr = false
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
group_imports = "Preserve"
reorder_modules = true
single_line_if_else_max_width = 130
space_after_colon = false
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
struct_lit_single_line = true
struct_lit_width = 32
trailing_comma = "Never"
trailing_semicolon = true
type_punctuation_density = "Compressed"
unstable_features = true
use_field_init_shorthand = false
use_small_heuristics = "Default"
where_single_line = true
wrap_comments = true